/** Declaration file generated by dts-gen */

export const ID_FIELD: string;

export function address(newValue: any): any;

export function collection(name: any, addMethods: any): any;

export function table(name: any): any;

export function token(newValue: any): any;

export namespace files {
    function get(path: any): any;

    function upload(form: any): any;

}

