name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install PNPM to run scripts
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen
          cache: 'pnpm'

      - name: Log in to Docker Hub (if needed)
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: pnpm docker:build

      - name: Check Docker Image
        run: | 
          pnpm docker:start
          pnpm docker:alive

      - name: Push Docker Image (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag firestorm-db-php:latest ${{ secrets.DOCKERHUB_USERNAME }}/firestorm-db-php:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/firestorm-db-php:latest
          