name: Documentation Publish

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: Build Documentation
    uses: ./.github/workflows/docs-build.yml

  deploy:
    name: Publish on GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download documentation
        uses: actions/download-artifact@v8
        with:
          name: documentation
          path: ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
