name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Publish on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src/index.js
          output_dir: ./out
          config_file: ./jsdoc.json
          template: docdash
          front_page: README.md

      - name: Copy images
        run: cp -r ./img ./out/img/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out