name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  publish_package:
    name: Publish npm Package
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: 'pnpm'

      - run: npm adduser --registry=https://registry.npmjs.org/
      - run: npm set //registry.npmjs.org/:_authToken "${{ secrets.NPM_TOKEN }}"
      - run: npm config get registry
      - run: npm config list
      - run: npm publish --provenance --access public
