name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  js-wrapper-test:
    name: Tests with PHP ${{ matrix.php }} & Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.4", "8.2"]
        node: ["22", "24", "26"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install developer dependencies
        run: pnpm install

      - name: Test da code
        run: pnpm php:tests

      - name: Comment coverage code to PR
        if: matrix.php == "8.2" && matrix.node == "26"
        uses: zgosalvez/github-actions-report-lcov@7.2.0
        with:
          coverage-files: coverage/lcov.*.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
