name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  js-wrapper-test:
    name: "Test JS wrapper"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen
          cache: 'pnpm'
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install developer dependencies
        run: pnpm install
      - name: Setup and run PHP server for API
        run: pnpm run php:start
      - name: Test da code
        run: pnpm test
      - name: Kill PHP server
        run: pnpm run php:stop
